name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-all:
    strategy:
      matrix:
        os: [ubuntu-latest]
      
    runs-on: ${{ matrix.os }}

    steps:
    - name: disable git crlf conversion
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - name: Install GTK dependencies
      run: >
          sudo apt-get update -q && sudo apt-get install --no-install-recommends -y libgtk-3-dev
    - name: Update pkg-config path
      run: echo "${HOME}/usr/lib/pkgconfig" >> $PKG_CONFIG_PATH
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  
